// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtHMt8EVwuQr2ud58mBjs4ap4ZsxaCFM',
    appId: '1:101700050440:android:fbc64514844e3fe4943bbd',
    messagingSenderId: '101700050440',
    projectId: 'bookcycle-c6800',
    storageBucket: 'bookcycle-c6800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomjEea9rDUbKJsm-lTHYfYNM7oY4Q9Ww',
    appId: '1:101700050440:ios:23bde41ada7e2e73943bbd',
    messagingSenderId: '101700050440',
    projectId: 'bookcycle-c6800',
    storageBucket: 'bookcycle-c6800.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomjEea9rDUbKJsm-lTHYfYNM7oY4Q9Ww',
    appId: '1:101700050440:ios:23bde41ada7e2e73943bbd',
    messagingSenderId: '101700050440',
    projectId: 'bookcycle-c6800',
    storageBucket: 'bookcycle-c6800.firebasestorage.app',
    iosBundleId: 'com.example.bookcycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2U82o6IwY6sjhcIHKqM2hiBcPfuYsBxc',
    appId: '1:101700050440:web:05b1dfbfdf7a0573943bbd',
    messagingSenderId: '101700050440',
    projectId: 'bookcycle-c6800',
    authDomain: 'bookcycle-c6800.firebaseapp.com',
    storageBucket: 'bookcycle-c6800.firebasestorage.app',
  );
}
